version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  redisdb:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  mongo-data:
    driver: local
