port: 3300    
database:
  mongo:
    url: sensitive
middleware:
  cors:
    activate: true
    origin:
      - 'http://localhost:4200'
      - 'https://dolphjs.com'
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowedHeaders:
      - 'Content-Type'
      - 'Authorization'
jsonLimit: 5mb
globalExceptionFilter: true 