port: 3300    
database:
  mongo:
    url: sensitive
middleware:
  cors:
    activate: true
    origin: '*'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowedHeaders:
      - 'Content-Type'
      - 'Authorization'
      - 'Access-Control-Allow-Origin'
      - 'Access-Control-Allow-Credentials'
jsonLimit: 5mb